name: school_me
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # localization
  flutter_localizations:
    sdk: flutter
  intl: any

  # state management
  flutter_hooks: ^0.18.6
  hooks_riverpod: ^2.3.4

  # generate code
  riverpod_annotation: ^2.0.4
  freezed_annotation: ^2.2.0

  # routing
  auto_route: ^6.3.0

  # local storage
  flutter_secure_storage: ^8.0.0

  # logging
  fimber: ^0.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: any
  riverpod_generator: ^2.1.6
  auto_route_generator: ^6.2.0
  riverpod_lint: ^1.2.0
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  dart_code_metrics: ^5.7.2

flutter:
  uses-material-design: true
  generate: true
